---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-opa
  labels:
    app: demo-opa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-opa
  template:
    metadata:
      labels:
        app: demo-opa
    spec:
      containers:
      - name: demo-opa
        image: nginx:1.25
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demo-opa
  labels:
    app: demo-opa
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: demo-opa
  type: NodePort    # This is what you have to change.

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-opa
spec:
  ingressClassName: nginx
  rules:
  - host: demo.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: demo-opa
           port:
             number: 80

---
apiVersion: v1
data:
  allow-backend-server-header: "true"
  use-forwarded-headers: "true"
kind: ConfigMap
metadata:
  name: nginx-configuration